# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mat_to_df_impl <- function(mat) {
    .Call(`_ipmr_mat_to_df_impl`, mat)
}

update_pop_state <- function(holder, current, iter) {
    .Call(`_ipmr_update_pop_state`, holder, current, iter)
}

