# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

right_mult_impl <- function(k, v) {
    .Call(`_ipmr_right_mult_impl`, k, v)
}

left_mult_impl <- function(k, v) {
    .Call(`_ipmr_left_mult_impl`, k, v)
}

mat_to_df_impl <- function(mat) {
    .Call(`_ipmr_mat_to_df_impl`, mat)
}

mean_kernel_impl <- function(holder) {
    .Call(`_ipmr_mean_kernel_impl`, holder)
}

update_pop_state <- function(holder, current, iter) {
    .Call(`_ipmr_update_pop_state`, holder, current, iter)
}

